### PR TITLE
Quick fix for files not being generated when they should

### LINKED ISSUE #9: v0.8.0 - service_bhvr.erl and service_client.erl files are not generated
In existing project using grpcbox and grpcbox_plugin noticed that recently when applying rebar3 grpc gen command, the following error message appeared:
Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.

Also, the following error was produced:
===> Error building 
<project>/_build/default/lib/<project>/ebin/<project>_pb.bea#
        none: error writing file: no such file or directory

And service_bhvr.erl and service_client.erl files are NOT generated at all.

After reverting back to version v0.7.0 of grpcbox_plugin - everything is Ok.

Erlang OTP 22. rebar3 version is 3.13.2 - compiling under Windows 10 Pro from powershell.

### PR DESCRIPTION
**Pull request by fenollp**
Fixes #9 
cf https://github.com/tsloughter/grpcbox_plugin/issues/9#issuecomment-829068166

### CODE REVIEW

**Comment by tsloughter** [comment]
Are these files never generated? I'm confused how it ever worked if this was the case.

**Comment by fenollp** [comment]
My project did not have this issue when I first set it up (early Jan 2020). Files were generating properly.
Since then something somewhere changed. I haven't looked into precisely what, sorry.

**Comment by vasu-dasari** [comment]
I have been using 0.7 version. I can try the patch on my private build later today.

**Comment by tsloughter** [comment]
Hm, I must have read this as changing from a `<` to `>` because I don't understand why I thought this change would mean shit never worked at all...

I was probably not sleeping :). If this works for you, I see no issues so will merge. @vasu-dasari have you tried it? I'm going to merge it now anyway, but curious to know.

**Comment by fenollp** [comment]
Hi @tsloughter 
Could you cut a Hex release with this in please? Here's the diff since last release: https://github.com/tsloughter/grpcbox_plugin/compare/v0.8.0...master

**Pull request merged**
